#!/bin/sh
### BEGIN INIT INFO  
# Provides:          syncGoogleDrive 
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the /dev/video0 
### END INIT INFO
case $1 in
    start)
        echo "starting  syncGoogleDrive...."
        start-stop-daemon --start --background --exec /home/pi/Desktop/test_2/test.py
    ;;
    stop)
        echo "stoping syncGoogleDrive...."
        start-stop-daemon --stop --name test.py
    ;;
    *)
        echo "Usage: $0 (start|stop)"
    ;;
esac